"""empty message

Revision ID: 998219c0c293
Revises: b48ad2d8a972
Create Date: 2022-07-17 14:05:39.486578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998219c0c293'
down_revision = 'b48ad2d8a972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
